### ISSUE TITLE
File is not uploaded to current directory but recently created one.

### ISSUE THREAD

**Issue by emard** [luc-github/Flashair-FM#8]
bug: files will not be uploaded to currently selected directory
but to recently created directory.

To upload to wanted directory, one must delete it if it exists,
create new and upload there.

linux, firefox

**Comment by luc-github** [comment]
Indeed - I have missed that - thank you - now upload directory is set before upload 
fixed in devt branch

Thank you

**Comment by emard** [comment]
I tested and it works correctly now
Much thanx for quick fix!
